### ISSUE TITLE
SMS synchronization problem in other user profiles in android

### ISSUE THREAD

**Issue by ghost** [Naveen3Singh/Simple-SMS-Messenger#86]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

Version 1.0.1

### Affected Android/Custom ROM version

Android 8.1

### Affected device model

Moto G5 Plus

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Switch to other user profile.
2. Make sure this app is installed there and all the permissions are granted to ther app and it is default SMS app.
3. Try to receive any OTP or any other SMS.

### Expected behavior

It should instantly prompt for new SMS without any delays.

### Actual behavior

In other user profiles, it takes really long time (around 5 minutes if lucky) and have to constantly close and open  app to get it synchronized with native android SMS database. It works perfectly fine within main profile tho if I switch to main profile at such time it shows new SMS notification there as expected but still no notification or new SMS in app in other profle. So issue is only within other user profiles.

### Additional information

I experienced similar issue with QK SMS app too but they have a button to synchronize it with native SMS database, I mentioned this issue earlier in issue #28 . But I face no sync issue for Google's messenger app if it is default SMS app.

**Comment by seankhl** [comment]
Thanks for opening this bug report. For me, if I know I'm getting a SMS and I open the SMS app in the non-main profile, I can get the message to appear. It still takes a few extra seconds beyond getting the notification for the SMS app in the other profile.

Sometimes I explicitly have to scroll up because the scrolling in the messages app doesn't scroll to the top and it appears as if there is no message there.

This can also happen in the view for the message for the specific number / conversation, where the app doesn't scroll to the bottom and it appears as if there's no message, but if I manually scroll down the newest message is there.

I have also seen the behavior where I actually do get a notification but the notification shows the text for the previous message from that contact!

All of these behaviors are only present in a non-main profile.

**Comment by tom93** [comment]
I can reproduce this on Android 8 and 14 (emulators).

Also, Android 8 crashes for me: after making Fossify Messages the default SMS app in the second user, the process com.android.systemui repeatedly throws NullPointerException calling 'com.android...NavigationBarFragment.onKeyguardOccludedChanged()'.

I've included the logs below. Some of the exceptions also happened when signed in as the "Owner" user; I used red ("-" prefix) to mark messages and events that only happen when signed in as the second user. I used green ("+" prefix) for actions I took. I'm not sure what the actual issue is and if there exceptions are relevant.

The Fossify Messages code is littered with empty `catch` statements that silence exceptions (added in commits such as d1fe3531e164da3803926afd8776d5fd39d919ec). This is bad practice and makes it very difficult to debug. I might write a PR to log those exceptions; I don't plan to continue debugging until that's done.

Aside: When signed in as the second user and using the AOSP Messaging app, it displays a notification that says "New message" rather than showing the contents of the message (also mentioned [here](https://forums.androidcentral.com/threads/text-message-issue-with-multiple-users.1059970/)).

---

Steps:

1. Boot a clean emulator.
2. Create a second user (on Android 8, when asked to set up user, click "not now"). Turn on phone call and SMS for that user. Switch to the second user.
3. Install Fossify Messages. (From the commandline: `adb shell pm list users` to find the user ID (1st column, for me the ID is 10), then `adb install --user 10 messages-2-foss-release.apk`, using GitHub release 1.0.1.)
4. Launch Fossify Messages.
5. When prompted, make Fossify Messages the default SMS app.

Android 14:

```diff
+(launch Fossify Messages)
 3404  3404 W ossify.messages: Unexpected CPU variant for x86: x86_64.
 3404  3404 W ossify.messages: Known variants: atom, sandybridge, silvermont, goldmont, goldmont-plus, tremont, kabylake, default
 3404  3404 E ossify.messages: Not starting debugger since process cannot load the jdwp agent.
 ...
 1035  1652 E DatabaseUtils: Writing exception to parcel
 1035  1652 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/draft from pid=3404, uid=1010141 requires android.permission.READ_SMS, or grantUriPermission()
 1035  1652 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:1011)
 1035  1652 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:813)
 1035  1652 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:253)
 1035  1652 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
 1035  1652 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1339)
 1035  1652 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1275)
 1035  1652 E DatabaseUtils: Writing exception to parcel
 1035  1652 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/draft from pid=3404, uid=1010141 requires android.permission.READ_SMS, or grantUriPermission()
 1035  1652 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:1011)
 1035  1652 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:813)
 1035  1652 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:253)
 1035  1652 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
 1035  1652 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1339)
 1035  1652 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1275)
 ...
+(make it the default SMS app)
 3404  3404 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
  823   854 W Looper  : Drained
-2617  2644 E DatabaseUtils: Writing exception to parcel
-2617  2644 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-2617  2644 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:716)
-2617  2644 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.checkForPermissionAndPrimaryUser(BlockedNumberProvider.java:672)
-2617  2644 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.enforceReadPermissionAndPrimaryUser(BlockedNumberProvider.java:662)
-2617  2644 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.query(BlockedNumberProvider.java:254)
-2617  2644 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1692)
-2617  2644 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:292)
-2617  2644 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
-2617  2644 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1339)
-2617  2644 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1275)
```

Android 8:

```diff
+(launch Fossify Messages)
-1825  1880 W ResourceType: Invalid package identifier when getting bag for resource number 0x7f12032d
-1825  1880 W ResourceType: No known package when getting value for resource number 0x7f11004d
-1825  1880 W ResourceType: No known package when getting value for resource number 0x7f0f000c
-1825  1880 W WindowManager: Token{9326683 ActivityRecord{1f5932 u10 org.fossify.messages/.activities.SplashActivity.Green t1000004}} failed creating starting window
-1825  1880 W WindowManager: android.content.res.Resources$NotFoundException: Resource ID #0x7f0f000c
-1825  1880 W WindowManager: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:213)
-1825  1880 W WindowManager: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:875)
-1825  1880 W WindowManager: 	at android.content.res.Resources.getDrawable(Resources.java:818)
-1825  1880 W WindowManager: 	at android.content.Context.getDrawable(Context.java:605)
-1825  1880 W WindowManager: 	at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
-1825  1880 W WindowManager: 	at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:742)
-1825  1880 W WindowManager: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2678)
-1825  1880 W WindowManager: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2066)
-1825  1880 W WindowManager: 	at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:2957)
-1825  1880 W WindowManager: 	at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:55)
-1825  1880 W WindowManager: 	at com.android.server.wm.AppWindowContainerController.lambda$-com_android_server_wm_AppWindowContainerController_4683(AppWindowContainerController.java:144)
-1825  1880 W WindowManager: 	at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.$m$0(Unknown Source:4)
-1825  1880 W WindowManager: 	at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.run(Unknown Source:0)
-1825  1880 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:789)
-1825  1880 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:98)
-1825  1880 W WindowManager: 	at android.os.Looper.loop(Looper.java:164)
-1825  1880 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:65)
-1825  1880 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
 3860  3860 W zygote64: Unexpected CPU variant for X86 using defaults: x86_64
-1825  1880 W ResourceType: Invalid package identifier when getting bag for resource number 0x7f12032d
-1825  1880 W ResourceType: No known package when getting value for resource number 0x7f11004d
-1825  1880 W ResourceType: No known package when getting value for resource number 0x7f0f000c
-1825  1880 W WindowManager: Token{6484c4 ActivityRecord{3a3f3d7 u10 org.fossify.messages/.activities.MainActivity t1000004}} failed creating starting window
-1825  1880 W WindowManager: android.content.res.Resources$NotFoundException: Resource ID #0x7f0f000c
-1825  1880 W WindowManager: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:213)
-1825  1880 W WindowManager: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:875)
-1825  1880 W WindowManager: 	at android.content.res.Resources.getDrawable(Resources.java:818)
-1825  1880 W WindowManager: 	at android.content.Context.getDrawable(Context.java:605)
-1825  1880 W WindowManager: 	at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
-1825  1880 W WindowManager: 	at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:742)
-1825  1880 W WindowManager: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2678)
-1825  1880 W WindowManager: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2066)
-1825  1880 W WindowManager: 	at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:2957)
-1825  1880 W WindowManager: 	at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:55)
-1825  1880 W WindowManager: 	at com.android.server.wm.AppWindowContainerController.lambda$-com_android_server_wm_AppWindowContainerController_4683(AppWindowContainerController.java:144)
-1825  1880 W WindowManager: 	at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.$m$0(Unknown Source:4)
-1825  1880 W WindowManager: 	at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.run(Unknown Source:0)
-1825  1880 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:789)
-1825  1880 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:98)
-1825  1880 W WindowManager: 	at android.os.Looper.loop(Looper.java:164)
-1825  1880 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:65)
-1825  1880 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
 2012  2901 E DatabaseUtils: Writing exception to parcel
 2012  2901 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/draft from pid=3860, uid=1010065 requires android.permission.READ_SMS, or grantUriPermission()
 2012  2901 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:633)
 2012  2901 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:503)
 2012  2901 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:215)
 2012  2901 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
 2012  2901 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:674)
 2012  2521 E DatabaseUtils: Writing exception to parcel
 2012  2521 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/draft from pid=3860, uid=1010065 requires android.permission.READ_SMS, or grantUriPermission()
 2012  2521 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:633)
 2012  2521 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:503)
 2012  2521 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:215)
 2012  2521 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
 2012  2521 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:674)
+(make it the default SMS app)
-2012  2521 E DatabaseUtils: Writing exception to parcel
-2012  2521 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/draft from pid=3860, uid=1010065 requires android.permission.READ_SMS, or grantUriPermission()
-2012  2521 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:633)
-2012  2521 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:503)
-2012  2521 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:215)
-2012  2521 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
-2012  2521 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:674)
-1959  1959 E AndroidRuntime: FATAL EXCEPTION: main
-1959  1959 E AndroidRuntime: Process: com.android.systemui, PID: 1959
-1959  1959 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.phone.NavigationBarFragment.onKeyguardOccludedChanged(boolean)' on a null object reference
-1959  1959 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.onKeyguardOccludedChanged(StatusBar.java:3843)
-1959  1959 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarKeyguardViewManager.setOccluded(StatusBarKeyguardViewManager.java:277)
-1959  1959 E AndroidRuntime: 	at com.android.systemui.keyguard.KeyguardViewMediator.handleSetOccluded(KeyguardViewMediator.java:1176)
-1959  1959 E AndroidRuntime: 	at com.android.systemui.keyguard.KeyguardViewMediator.-wrap14(Unknown Source:0)
-1959  1959 E AndroidRuntime: 	at com.android.systemui.keyguard.KeyguardViewMediator$4.handleMessage(KeyguardViewMediator.java:1531)
-1959  1959 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
-1959  1959 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
-1959  1959 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
-1959  1959 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
-1959  1959 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
-1959  1959 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
-(omitted many other messages related to system crash)
-(repeats)
-...
-(permission popup: send and view SMS)
+(approve permission)
-(permission popup: access contacts)
+(approve permission)
-...
-4192  4241 E DatabaseUtils: Writing exception to parcel
-4192  4241 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4241 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-4192  4241 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.checkForPermissionAndPrimaryUser(BlockedNumberProvider.java:528)
-4192  4241 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.enforceReadPermissionAndPrimaryUser(BlockedNumberProvider.java:518)
-4192  4241 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.query(BlockedNumberProvider.java:249)
-4192  4241 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1149)
-4192  4241 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
-4192  4241 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
-4192  4241 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:674)
+(unlock the screen)
```

On Android 8, I get more exceptions when I open a conversation as the second user:

```diff
+(tap conversation)
-2012  2316 E MmsSmsProvider: getThreadId: NO receipients specified -- NOT creating thread
-2012  2316 E MmsSmsProvider: java.lang.Exception
-2012  2316 E MmsSmsProvider: 	at com.android.providers.telephony.MmsSmsProvider.getThreadId(MmsSmsProvider.java:671)
-2012  2316 E MmsSmsProvider: 	at com.android.providers.telephony.MmsSmsProvider.query(MmsSmsProvider.java:376)
-2012  2316 E MmsSmsProvider: 	at android.content.ContentProvider.query(ContentProvider.java:1057)
-2012  2316 E MmsSmsProvider: 	at android.content.ContentProvider.query(ContentProvider.java:1149)
-2012  2316 E MmsSmsProvider: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
-2012  2316 E MmsSmsProvider: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
-2012  2316 E MmsSmsProvider: 	at android.os.Binder.execTransact(Binder.java:674)
-4192  4262 E DatabaseUtils: Writing exception to parcel
-4192  4262 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4262 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-3860  4266 E EventBus: Could not dispatch event: class org.fossify.messages.models.Events$RefreshMessages to subscribing class class org.fossify.messages.activities.ThreadActivity
-3860  4266 E EventBus: java.lang.SecurityException: getActiveSubscriptionInfoList: Neither user 1010065 nor current process has android.permission.READ_PHONE_STATE.
-3860  4266 E EventBus: 	at android.os.Parcel.readException(Parcel.java:1943)
-3860  4266 E EventBus: 	at android.os.Parcel.readException(Parcel.java:1889)
-3860  4266 E EventBus: 	at com.android.internal.telephony.ISub$Stub$Proxy.getActiveSubscriptionInfoList(ISub.java:559)
-3860  4266 E EventBus: 	at android.telephony.SubscriptionManager.getActiveSubscriptionInfoList(SubscriptionManager.java:626)
-3860  4266 E EventBus: 	at org.fossify.messages.activities.ThreadActivity.getThreadItems(ThreadActivity.kt:1104)
-3860  4266 E EventBus: 	at org.fossify.messages.activities.ThreadActivity.setupAdapter(ThreadActivity.kt:453)
-3860  4266 E EventBus: 	at org.fossify.messages.activities.ThreadActivity.refreshMessages(ThreadActivity.kt:1574)
-3860  4266 E EventBus: 	at java.lang.reflect.Method.invoke(Native Method)
-3860  4266 E EventBus: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
-3860  4266 E EventBus: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
-3860  4266 E EventBus: 	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
-3860  4266 E EventBus: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
-3860  4266 E EventBus: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
-3860  4266 E EventBus: 	at java.lang.Thread.run(Thread.java:764)
-3860  3860 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
-4192  4262 E DatabaseUtils: Writing exception to parcel
-4192  4262 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4262 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-4192  4241 E DatabaseUtils: Writing exception to parcel
-4192  4241 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4241 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-(permission popup: make and manage phone calls)
+(approve permission)
-3860  3860 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
-4192  4262 E DatabaseUtils: Writing exception to parcel
-4192  4262 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4262 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-4192  4241 E DatabaseUtils: Writing exception to parcel
-4192  4241 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4241 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-4192  4212 E DatabaseUtils: Writing exception to parcel
-4192  4212 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4212 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-3860  3860 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
-4192  4210 E DatabaseUtils: Writing exception to parcel
-4192  4210 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4210 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-4192  4210 E DatabaseUtils: Writing exception to parcel
-4192  4210 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4210 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-3860  3860 E ActivityThread: Failed to find provider info for org.fossify.commons.contactsprovider
-4192  4208 E DatabaseUtils: Writing exception to parcel
-4192  4208 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4208 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-4192  4262 E DatabaseUtils: Writing exception to parcel
-4192  4262 E DatabaseUtils: java.lang.SecurityException: The current user cannot perform this operation
-4192  4262 E DatabaseUtils: 	at com.android.providers.blockednumber.BlockedNumberProvider.throwCurrentUserNotPermittedSecurityException(BlockedNumberProvider.java:572)
-...
-(got taken to lock screen)
+(unlock)
```

**Comment by tom93** [comment]
*(Just to clarify terminology, when I wrote "I can reproduce this" it means that the issue also happens for me in the emulators.)*

As I wrote, there is definitely an issue with Android 8 itself (I used 8.0.0), but if you run into that issue it should be very obvious (you will be taken to the lockscreen). Since the native AOSP Messaging app works fine (apart from not showing the message contents in the notification), I think it is very likely that there are also bugs in the Fossify app. However, as I said, I'm not interested in debugging further until the exception silencing issue is resolved (I'll try to get started on that soon). I don't have any suitable test devices, but I don't see any need (yet) because the issue also happens in an emulator.
